// Code generated by hertz generator.

package video

import (
	"context"

	video "github.com/LingeringAutumn/Yijie/app/gateway/model/api/video"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// SubmitVideo .
// @router api/v1/video/submit [POST]
func SubmitVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.VideoSubmissionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.VideoSubmissionResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetVideo .
// @router api/v1/video/get [GET]
func GetVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.VideoDetailRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.VideoDetailResponse)

	c.JSON(consts.StatusOK, resp)
}

// SearchVideo .
// @router api/v1/video/search [GET]
func SearchVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.VideoSearchRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.VideoSearchResponse)

	c.JSON(consts.StatusOK, resp)
}

// TrendingVideo .
// @router api/v1/video/trending [GET]
func TrendingVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.VideoTrendingRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.VideoTrendingResponse)

	c.JSON(consts.StatusOK, resp)
}
