// Code generated by hertz generator.

package user_behaviour

import (
	"github.com/cloudwego/hertz/pkg/app"

	"github.com/LingeringAutumn/Yijie/app/gateway/mw"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		mw.Auth(),
	}
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likevideoMw() []app.HandlerFunc {
	// your code...
	return nil
}
