// Code generated by Kitex v0.12.3. DO NOT EDIT.

package likeservice

import (
	"context"
	"errors"
	user_behaviour "github.com/LingeringAutumn/Yijie/kitex_gen/user_behaviour"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"LikeVideo": kitex.NewMethodInfo(
		likeVideoHandler,
		newLikeServiceLikeVideoArgs,
		newLikeServiceLikeVideoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	likeServiceServiceInfo                = NewServiceInfo()
	likeServiceServiceInfoForClient       = NewServiceInfoForClient()
	likeServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return likeServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return likeServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return likeServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "LikeService"
	handlerType := (*user_behaviour.LikeService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "user_behaviour",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.12.3",
		Extra:           extra,
	}
	return svcInfo
}

func likeVideoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user_behaviour.LikeServiceLikeVideoArgs)
	realResult := result.(*user_behaviour.LikeServiceLikeVideoResult)
	success, err := handler.(user_behaviour.LikeService).LikeVideo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLikeServiceLikeVideoArgs() interface{} {
	return user_behaviour.NewLikeServiceLikeVideoArgs()
}

func newLikeServiceLikeVideoResult() interface{} {
	return user_behaviour.NewLikeServiceLikeVideoResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) LikeVideo(ctx context.Context, req *user_behaviour.VideoLikeRequest) (r *user_behaviour.VideoLikeResponse, err error) {
	var _args user_behaviour.LikeServiceLikeVideoArgs
	_args.Req = req
	var _result user_behaviour.LikeServiceLikeVideoResult
	if err = p.c.Call(ctx, "LikeVideo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
