// Code generated by Kitex v0.12.3. DO NOT EDIT.

package likeservice

import (
	"context"
	user_behavior "github.com/LingeringAutumn/Yijie/kitex_gen/user_behavior"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	LikeVideo(ctx context.Context, req *user_behavior.VideoLikeRequest, callOptions ...callopt.Option) (r *user_behavior.VideoLikeResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kLikeServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kLikeServiceClient struct {
	*kClient
}

func (p *kLikeServiceClient) LikeVideo(ctx context.Context, req *user_behavior.VideoLikeRequest, callOptions ...callopt.Option) (r *user_behavior.VideoLikeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.LikeVideo(ctx, req)
}
