// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"

	api_user "github.com/LingeringAutumn/Yijie/app/gateway/router/api/user"
	api_user_behaviour "github.com/LingeringAutumn/Yijie/app/gateway/router/api/user_behaviour"
	api_video "github.com/LingeringAutumn/Yijie/app/gateway/router/api/video"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	api_user_behaviour.Register(r)

	api_video.Register(r)

	api_user.Register(r)
}
